"use client";

import { useMemo, useState } from "react";

type Job = {
  company: string; title: string; region: "US" | "Europe" | "India" | "Global";
  location: string; salary?: string; level: string; lane: string; fit: string;
  signals: string[]; posted: string; url: string; featured?: boolean;
};

const previousSnapshot: Job[] = [
  {company:"LiveKit",title:"Forward Deployed Engineer",region:"India",location:"Remote · India",level:"Mid–Senior",lane:"Real-time AI",fit:"Builder who likes messy integrations, production voice/video, and direct customer ownership.",signals:["Python","Go / Rust","Agentic AI"],posted:"11d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-cb0d61f1",featured:true},
  {company:"LiveKit",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$180k–$320k",level:"Senior",lane:"Real-time AI",fit:"High-agency product engineer comfortable turning customer workflows into reusable platform capability.",signals:["Python","Go / Rust","OpenAI"],posted:"9d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-4781a085",featured:true},
  {company:"JetBrains",title:"Principal Forward Deployed Engineer",region:"Europe",location:"Remote · Germany",level:"Principal",lane:"AI-native dev",fit:"Technical leader who can embed with engineering teams and reshape how software gets built with AI.",signals:["AI coding","Enterprise","Architecture"],posted:"3d",url:"https://www.fwddeploy.com/jobs/principal-forward-deployed-engineer-ai-native-software-development-m-f-d-0d411ab9",featured:true},
  {company:"Zendesk",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$200k–$300k",level:"Senior",lane:"Customer operations",fit:"Strong full-stack builder who can connect AI agents to real support operations and prove business value.",signals:["Agents","APIs","Enterprise SaaS"],posted:"8d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-ad388423"},
  {company:"Leap",title:"Forward Deployed Engineer, Care Operations",region:"US",location:"Remote · United States",salary:"$153k–$189k",level:"Mid–Senior",lane:"Healthtech",fit:"Best for someone who enjoys operational systems, regulated data, and high-empathy customer discovery.",signals:["Healthcare","Workflows","Data"],posted:"9d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-care-operations-05b60b5b"},
  {company:"Maybern",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$180k–$270k",level:"Senior",lane:"Fintech",fit:"Engineer who can model complex private-markets workflows and earn trust with demanding finance teams.",signals:["Fintech","Data models","Full-stack"],posted:"8d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-remote-f15a4279"},
  {company:"Nebius",title:"Forward Deployed Engineer — Physical AI",region:"US",location:"Remote · United States",salary:"$169.9k–$254.9k",level:"Senior",lane:"Physical AI",fit:"Infrastructure-minded AI engineer drawn to robotics, accelerated compute, and customer production environments.",signals:["Kubernetes","Python","Rust"],posted:"7d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-physical-ai-636f436e"},
  {company:"Hatch",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$162k–$219k",level:"Mid–Senior",lane:"Integrations",fit:"Pragmatic integration builder who can ship the workflows standard onboarding cannot handle.",signals:["APIs","Consulting","Workflows"],posted:"11d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-b5c74f67"},
  {company:"OpenHands",title:"Forward Deployed Engineer",region:"Global",location:"Remote · location flexible",salary:"$150k–$215k",level:"Senior",lane:"AI coding agents",fit:"Open-source-minded engineer who can turn coding-agent capability into reliable customer deployments.",signals:["Python","Rust","CI/CD"],posted:"10d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-8bf26185",featured:true},
  {company:"IFS",title:"Forward Deployed AI Engineer",region:"US",location:"Remote · United States",salary:"$150k–$170k + bonus",level:"Mid–Senior",lane:"Enterprise agents",fit:"Applied AI generalist who can move from discovery to RAG, integrations, testing, and handoff.",signals:["Python","RAG","LangChain"],posted:"8d",url:"https://www.fwddeploy.com/jobs/forward-deployed-ai-engineer-e6a5a320"},
  {company:"Domino Data Lab",title:"Forward Deployed Engineer, Life Sciences",region:"US",location:"Remote · United States",level:"Senior",lane:"Life sciences",fit:"ML platform engineer who can work with scientific teams and productionize regulated AI workflows.",signals:["MLOps","Life sciences","Enterprise"],posted:"7d",url:"https://www.fwddeploy.com/s/remote-jobs"},
  {company:"Infinitus",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Senior",lane:"Healthcare voice AI",fit:"Customer-facing engineer interested in automating healthcare calls without losing operational rigor.",signals:["Voice AI","Healthcare","Integrations"],posted:"8d",url:"https://www.fwddeploy.com/s/remote-jobs"},
  {company:"GenLogs",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Mid–Senior",lane:"Supply-chain intelligence",fit:"Data-heavy builder who enjoys deploying ML into physical-world logistics and investigative workflows.",signals:["Python","SQL","ML"],posted:"8d",url:"https://www.fwddeploy.com/s/remote-jobs"},
  {company:"Second Front",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$105k–$141k",level:"Mid–Senior",lane:"Defense / regulated",fit:"Systems engineer comfortable with government constraints, cloud deployment, and mission-critical operations.",signals:["AWS / GCP","Kubernetes","Security"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"n8n",title:"Forward Deployed Engineer",region:"Europe",location:"Remote · Germany / Europe",level:"Senior",lane:"Workflow automation",fit:"Automation-native engineer who likes open source, professional services, and making integrations repeatable.",signals:["AI","GitHub","Professional services"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"Rimini Street",title:"Forward Deployed Engineer, Agentic AI",region:"US",location:"Remote · United States",salary:"$140k–$180k",level:"Principal / Senior",lane:"Enterprise agents",fit:"Experienced enterprise technologist who can navigate legacy stacks and still ship modern agentic systems.",signals:["AWS / Azure","TypeScript","Enterprise"],posted:"1d",url:"https://deployaijobs.com/jobs"},
  {company:"Kinaxis",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Senior",lane:"Supply chain",fit:"Data engineer who can translate planning problems into deployable analytics and AI systems.",signals:["Airflow","BigQuery","Kafka"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"Moder",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Mid–Senior",lane:"Applied AI",fit:"Hands-on generalist who can span data, LLM application work, and customer implementation.",signals:["Python","SQL","Spark"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"Deployment.io",title:"Forward Deployed Engineer",region:"Global",location:"Remote · US or India",level:"2–5 years",lane:"Cloud delivery",fit:"Clear-writing engineer who can plan, build, verify, and ship into customer-owned clouds end to end.",signals:["Cloud","Agents","Customer ownership"],posted:"Evergreen",url:"https://deployment.io/careers/",featured:true},
  {company:"Tribe AI",title:"Forward Deployed CTO",region:"US",location:"Remote · United States",salary:"$300k–$450k",level:"Executive",lane:"AI transformation",fit:"",signals:["AI strategy","Delivery","Executive"],posted:"4d",url:"https://www.fwddeploy.com/s/remote-jobs"},
  {company:"Zoom",title:"AI Deployment Strategist",region:"US",location:"Remote · United States",level:"Senior",lane:"Enterprise AI",fit:"",signals:["AI adoption","Workflows","Enterprise"],posted:"Current",url:"https://www.fwddeploy.com/s/remote-jobs"},
  {company:"Jobgether",title:"Senior Forward Deployed Engineer",region:"Global",location:"Remote · Multiple countries",level:"Senior",lane:"Remote build",fit:"",signals:["Full-stack","Customer delivery","AI"],posted:"6d",url:"https://www.fwddeploy.com/s/remote-jobs"},
  {company:"Qualified Health",title:"Senior Forward Deployed Data Engineer",region:"US",location:"Remote · United States",level:"Senior",lane:"Healthcare data",fit:"",signals:["Data modernization","Healthcare","Cloud"],posted:"7d",url:"https://www.fwddeploy.com/s/remote-jobs"},
  {company:"Endava",title:"Forward Deployed Engineer (Palantir)",region:"US",location:"Remote · United States",level:"Senior",lane:"Data platforms",fit:"",signals:["Palantir","Data","Consulting"],posted:"15d",url:"https://www.fwddeploy.com/s/remote-jobs"},
  {company:"Atos",title:"Forward Deployed Solution Architect",region:"Europe",location:"Remote · Germany",level:"Senior",lane:"Modern data platforms",fit:"",signals:["Data platforms","Architecture","Cloud"],posted:"8d",url:"https://www.fwddeploy.com/s/remote-jobs"},
  {company:"Formant",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Mid–Senior",lane:"Robotics",fit:"",signals:["Robotics","Integrations","IoT"],posted:"1mo",url:"https://www.fwddeploy.com/s/remote-jobs?page=2"},
  {company:"Atlassian",title:"Principal Forward Deployed Engineer, AI",region:"Europe",location:"Remote · United Kingdom",level:"Principal",lane:"Enterprise AI",fit:"",signals:["AI","Architecture","Enterprise"],posted:"1mo",url:"https://www.fwddeploy.com/s/remote-jobs?page=2"},
  {company:"Atlassian",title:"Principal Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Principal",lane:"Enterprise software",fit:"",signals:["Platform","Architecture","Delivery"],posted:"1mo",url:"https://www.fwddeploy.com/s/remote-jobs?page=2"},
  {company:"Statisfy",title:"Forward Deployed Engineer",region:"India",location:"Remote · India",level:"Mid–Senior",lane:"Revenue AI",fit:"",signals:["AI","Customer systems","Full-stack"],posted:"1mo",url:"https://www.fwddeploy.com/s/remote-jobs?page=2",featured:true},
  {company:"Diné Development",title:"Forward Deployed Innovation Strategist",region:"US",location:"Remote · United States",level:"Senior",lane:"Public sector",fit:"",signals:["Innovation","Government","Delivery"],posted:"3mo",url:"https://www.fwddeploy.com/s/remote-jobs?page=2"},
  {company:"Aimpoint Digital",title:"Forward Deployed AI Engineer — Claude",region:"US",location:"Remote · United States",level:"Senior",lane:"Enterprise agents",fit:"",signals:["Claude","Agents","Governance"],posted:"2d",url:"https://www.indeed.com/viewjob?jk=5717194645b638ad"},
  {company:"PolyAI",title:"Forward Deployed AI Engineer",region:"US",location:"Remote · PST timezone",salary:"$150k–$190k",level:"Mid–Senior",lane:"Voice AI",fit:"",signals:["Python","Docker","Kubernetes"],posted:"3w",url:"https://www.indeed.com/viewjob?jk=abe68f61f886f2f0"},
  {company:"Speechify",title:"Forward Deployment Engineer",region:"US",location:"Remote · United States",salary:"$140k–$200k",level:"Mid–Senior",lane:"Speech AI",fit:"",signals:["Voice","Integrations","AI"],posted:"Current",url:"https://www.indeed.com/q-Forward-Deployed-Engineer-l-Remote-jobs.html"},
  {company:"Novartis",title:"Director, AI Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$194.6k–$361.4k",level:"Director",lane:"Life sciences AI",fit:"",signals:["AI delivery","Leadership","Healthcare"],posted:"Current",url:"https://www.indeed.com/q-Forward-Deployed-Engineer-l-Remote-jobs.html"},
  {company:"Okta",title:"Senior Forward Deployed Engineer — AI Agents",region:"US",location:"Remote · United States",salary:"$200k–$275k",level:"Senior",lane:"Identity for agents",fit:"",signals:["Identity","Security","Agents"],posted:"Current",url:"https://www.indeed.com/q-Forward-Deployed-Engineer-l-Remote-jobs.html"},
  {company:"Aledade",title:"Senior Software Engineer II — Forward Deployed AI",region:"US",location:"Remote · United States",level:"Senior",lane:"Healthcare AI",fit:"",signals:["Full-stack","Healthcare","AI"],posted:"Current",url:"https://www.indeed.com/q-Forward-Deployed-Engineer-l-Remote-jobs.html"},
  {company:"Aledade",title:"Senior Software Engineer I — Forward Deployed AI",region:"US",location:"Remote · United States",level:"Senior",lane:"Healthcare AI",fit:"",signals:["Production AI","Data","Customer delivery"],posted:"Current",url:"https://www.indeed.com/q-Forward-Deployed-Engineer-l-Remote-jobs.html"},
  {company:"Smartsheet",title:"Senior Forward Deployed AI Engineer",region:"US",location:"Remote eligible · United States",salary:"$227.5k–$245k",level:"Senior",lane:"Enterprise workflows",fit:"",signals:["Architecture","Cloud","AI"],posted:"Current",url:"https://www.indeed.com/q-Forward-Deployed-Engineer-l-Remote-jobs.html"},
  {company:"Spellbook",title:"Forward Deployed Engineer",region:"Global",location:"Remote · Canada",level:"Mid–Senior",lane:"Legal AI",fit:"",signals:["Legaltech","Integrations","AI"],posted:"2w",url:"https://jobs.ashbyhq.com/spellbook.com/d92285f3-73a5-4ad1-8b1a-df1d2ab034df/"},
  {company:"Arize AI",title:"Forward Deployed AI Engineer, EMEA",region:"Europe",location:"Remote · EMEA",salary:"$155k–$225k",level:"Senior",lane:"AI observability",fit:"",signals:["Evaluation","Observability","GenAI"],posted:"1d",url:"https://www.indeed.com/viewjob?jk=06b30612fba469be"},
  {company:"Growth Protocol",title:"Forward Deployed Engineer",region:"US",location:"Remote · US or Canada",salary:"$150k–$180k",level:"Senior",lane:"Enterprise reasoning",fit:"",signals:["Agentic AI","Data activation","Delivery"],posted:"2mo",url:"https://jobs.ashbyhq.com/growthprotocol/bdb23236-dbb5-48a4-8f5c-3325fd03c8ee"},
  {company:"Kilo Code",title:"Forward Deployed Engineer",region:"Global",location:"Remote",level:"Mid–Senior",lane:"AI coding agents",fit:"",signals:["Open source","Coding agents","Enterprise"],posted:"2mo",url:"https://jobs.ashbyhq.com/kilocode/95a3e9e1-375b-4916-994f-e0fbff163c4d"},
  {company:"Outmarket",title:"Forward Deployed AI Engineer",region:"Global",location:"Remote · US or India",level:"Mid–Senior",lane:"Insurance AI",fit:"",signals:["AI","Insurance","Product"],posted:"1d",url:"https://outmarket.ai/careers/forward-deployed-ai-engineer",featured:true},
  {company:"Duvo",title:"Forward Deployed Engineer",region:"US",location:"Remote · US East Coast",level:"Mid–Senior",lane:"AI agents",fit:"",signals:["Agents","Integrations","Data"],posted:"2mo",url:"https://jobs.ashbyhq.com/duvo/4eaf5dd3-8479-4f5e-8fc4-5cdc919441af"},
  {company:"Rerun",title:"Forward Deployed Engineer",region:"US",location:"Remote · US West Coast",level:"Mid–Senior",lane:"Developer tools",fit:"",signals:["Rust","Visualization","Customer delivery"],posted:"3w",url:"https://jobs.ashbyhq.com/rerun/ee28fed0-9ada-40ac-b828-f1ed633f60e6"},
  {company:"Catena",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Senior",lane:"Data workflows",fit:"",signals:["Data","Product","Customer ownership"],posted:"3w",url:"https://jobs.ashbyhq.com/catena/a26bbbb9-1b60-40f1-a772-2f4214c784c7"},
  {company:"Google Cloud",title:"Forward Deployed Engineer III, Generative AI",region:"US",location:"Remote eligible · United States",level:"Mid–Senior",lane:"Generative AI",fit:"",signals:["GCP","GenAI","Enterprise"],posted:"3d",url:"https://www.google.com/about/careers/applications/jobs/results/127965694384841414-forward-deployed-engineer-iii-generative-ai-google-cloud"},
  {company:"Remote",title:"Forward Deployed Engineer (AI)",region:"Global",location:"Remote · Distributed",level:"Senior",lane:"HR platform AI",fit:"",signals:["AI","Workflows","Integrations"],posted:"2w",url:"https://www.fwddeploy.com/s/remote-jobs"},
  {company:"Statecraft",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$160k–$220k",level:"Mid–Senior",lane:"Govtech",fit:"",signals:["Public sector","Full-stack","Delivery"],posted:"1mo",url:"https://careers.statecraft.ai/jobs/forward-deployed-engineer"},
  {company:"Deepgram",title:"Senior Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Senior",lane:"Voice AI",fit:"",signals:["Speech AI","Python","Production ML"],posted:"Current",url:"https://deepgram.com/careers"},
  {company:"Flock Safety",title:"Forward Deployment Engineer",region:"US",location:"Remote eligible · United States",level:"Mid–Senior",lane:"Public safety",fit:"",signals:["Edge systems","Hardware","Operations"],posted:"Current",url:"https://www.flocksafety.com/careers"},
  {company:"Primer AI",title:"Forward Deployed Engineer",region:"Europe",location:"Remote · Germany",level:"Senior",lane:"Decision intelligence",fit:"",signals:["NLP","AI","Government"],posted:"Current",url:"https://primer.ai/careers"},
  {company:"Juniper Square",title:"Senior Forward Deployed Engineer, AI",region:"US",location:"Remote · US or Canada",salary:"$170k–$220k",level:"Senior",lane:"Fintech AI",fit:"",signals:["AI","Private markets","Enterprise"],posted:"1mo",url:"https://www.junipersquare.com/careers"},
  {company:"Neara",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$130k–$200k",level:"Senior",lane:"Infrastructure modeling",fit:"",signals:["Python","TypeScript","Digital twins"],posted:"2d",url:"https://deployaijobs.com/jobs"},
  {company:"Hatch",title:"Senior Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Senior",lane:"Conversational AI",fit:"",signals:["Integrations","AI","Customer systems"],posted:"Current",url:"https://jobs.ashbyhq.com/hatch"},
];

// Refreshed 28 July 2026. Every entry below appeared in a current specialist
// feed or on a live employer page during the refresh. Older snapshot entries
// remain above for audit history but are not rendered.
const jobs: Job[] = [
  {company:"Google Cloud",title:"Forward Deployed Engineer III, Applied AI",region:"US",location:"United States · Multiple cities",salary:"$174k–$253k",level:"Senior",lane:"Applied AI",fit:"",signals:["GCP","GenAI","MLOps"],posted:"Today",url:"https://deployaijobs.com/jobs/forward-deployed-engineer-iii-google-cloud-applied-ai-google-san-francisco-california-22749/",featured:true},
  {company:"Google Cloud",title:"Forward Deployed Engineer IV, Applied AI",region:"US",location:"United States · Multiple cities",salary:"$207k–$301k",level:"Senior",lane:"Applied AI",fit:"",signals:["GCP","Agents","Enterprise"],posted:"Today",url:"https://deployaijobs.com/jobs/forward-deployed-engineer-iv-applied-ai-google-cloud-google-austin-texas-22740/",featured:true},
  {company:"GitLab",title:"Staff Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$254k–$297k",level:"Staff",lane:"DevSecOps",fit:"",signals:["Kubernetes","Terraform","TypeScript"],posted:"Today",url:"https://deployaijobs.com/jobs/staff-forward-deployed-engineer-gitlab-united-states-north-america-remote-22729/",featured:true},
  {company:"Vercel",title:"Director of Forward Deployed Engineering",region:"US",location:"Remote · NY / TX / CA",salary:"$240k–$300k",level:"Director",lane:"Developer platform",fit:"",signals:["TypeScript","React","Leadership"],posted:"Today",url:"https://deployaijobs.com/jobs/director-of-forward-deployed-engineering-vercel-new-york-texas-remote-22725/"},
  {company:"Thomson Reuters",title:"Senior Software Engineer — CoCounsel FDE",region:"US",location:"Remote · United States",salary:"$109k–$203k",level:"Senior",lane:"Legal AI",fit:"",signals:["Python","LLM","Prompt engineering"],posted:"Today",url:"https://deployaijobs.com/jobs/senior-software-engineer-legal-cocounsel-forward-deployed-engineering-thomson-reuters-frisco-texas-remote-22747/"},
  {company:"Thomson Reuters",title:"Software Engineer — AI CoCounsel FDE",region:"US",location:"Remote · United States",salary:"$109k–$203k",level:"Mid",lane:"Legal AI",fit:"",signals:["Python","Cloud","LLM"],posted:"Today",url:"https://deployaijobs.com/jobs/software-engineer-ai-cocounsel-forward-deployed-engineering-thomson-reuters-frisco-texas-remote-22741/"},
  {company:"Keyrus",title:"Forward Deployed AI Engineer",region:"Europe",location:"Remote · Portugal",salary:"€65k–€78k",level:"Mid–Senior",lane:"Applied AI",fit:"",signals:["AI","Data","Consulting"],posted:"Today",url:"https://deployaijobs.com/jobs/forward-deployed-ai-engineer-keyrus-lisbon-portugal-remote-22746/"},
  {company:"Keyrus",title:"Forward Deployed AI Engineer",region:"Europe",location:"Remote · United Kingdom",salary:"£87k–£105k",level:"Mid–Senior",lane:"Applied AI",fit:"",signals:["AI","Data","Enterprise"],posted:"Today",url:"https://deployaijobs.com/jobs/forward-deployed-ai-engineer-keyrus-london-england-remote-22739/"},
  {company:"Hightouch",title:"Forward Deployed Analytics Engineer",region:"Global",location:"Remote · North America",salary:"$100k–$160k",level:"Senior",lane:"Data activation",fit:"",signals:["SQL","LLM","Analytics"],posted:"Today",url:"https://deployaijobs.com/jobs/forward-deployed-analytics-engineer-hightouch-north-america-remote-22744/"},
  {company:"Accenture",title:"Forward Deployed Engineer Specialist",region:"Europe",location:"Rome · Italy",salary:"€32k–€54.9k",level:"Mid–Senior",lane:"Enterprise AI",fit:"",signals:["Claude","Terraform","Microservices"],posted:"Today",url:"https://deployaijobs.com/jobs/forward-deployed-engineer-specialist-accenture-rome-lazio-22733/"},
  {company:"Jobgether",title:"Forward Deployed Engineer — Agents",region:"India",location:"Remote · India",level:"Mid–Senior",lane:"AI agents",fit:"",signals:["Agents","Full-stack","Customer delivery"],posted:"5d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-agents-c1e7e4b2",featured:true},
  {company:"KDCI",title:"Forward Deployed Engineer",region:"Global",location:"Remote · Philippines",level:"Mid–Senior",lane:"Customer engineering",fit:"",signals:["Integrations","Delivery","APIs"],posted:"8d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-99671fc5"},
  {company:"Intellectsoft",title:"Forward Deployed Engineer (IR-537)",region:"Global",location:"Remote",level:"Mid–Senior",lane:"Software delivery",fit:"",signals:["Full-stack","Cloud","Consulting"],posted:"4d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-ir-537-d550176a"},
  {company:"ElevenLabs",title:"Forward Deployed Engineer — ANZ",region:"Global",location:"Remote · Singapore",level:"Mid–Senior",lane:"Voice AI",fit:"",signals:["Python","APIs","Voice AI"],posted:"8d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-software-engineer-anz-8fc2480a",featured:true},
  {company:"Istari Digital",title:"Forward Deployed Engineer — International",region:"Global",location:"Remote · International",salary:"$143k–$165k",level:"Mid–Senior",lane:"Digital engineering",fit:"",signals:["Cloud","Systems","Customer delivery"],posted:"7d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-commercial-international-afa4c887"},
  {company:"CROZ DACH",title:"Forward Deployed Engineer — AI",region:"Europe",location:"Remote · Germany",level:"Mid–Senior",lane:"Applied AI",fit:"",signals:["AI","German","Consulting"],posted:"3d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-ai-w-m-d-in-voll-oder-teilzeit-3e854919"},
  {company:"Athena",title:"Forward Deployed Engineer, Routines",region:"US",location:"Remote · United States",level:"Mid–Senior",lane:"Workflow AI",fit:"",signals:["Automation","Product","AI"],posted:"12d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-routines-aeb9f212"},
  {company:"Atlas Technica",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Mid–Senior",lane:"IT platforms",fit:"",signals:["Infrastructure","Cloud","Customer delivery"],posted:"6d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-13c99bfc"},
  {company:"Kognitos",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Mid–Senior",lane:"Process automation",fit:"",signals:["AI","Automation","Enterprise"],posted:"15d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-43bc408f"},
  {company:"Convr",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Mid–Senior",lane:"Insurance AI",fit:"",signals:["AI","Data","Insurance"],posted:"11d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-a9214a88"},
  {company:"Clera",title:"Founding Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$110k–$135k",level:"Founding",lane:"Vertical SaaS",fit:"",signals:["Full-stack","Customer success","Product"],posted:"7d",url:"https://www.fwddeploy.com/jobs/founding-forward-deployed-engineer-53cfcb31"},
  {company:"Resultant",title:"Forward Deployed AI Engineer",region:"US",location:"Remote · United States",level:"Mid–Senior",lane:"Applied AI",fit:"",signals:["AI","Data","Consulting"],posted:"14d",url:"https://www.fwddeploy.com/jobs/forward-deployed-ai-engineer-0e601cdc"},
  {company:"ElevenLabs",title:"Forward Deployed Engineer — Brazil",region:"Global",location:"Remote · Brazil",level:"Mid–Senior",lane:"Voice AI",fit:"",signals:["Python","APIs","Voice AI"],posted:"8d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-software-engineer-8869cc63"},
  {company:"Teleport",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$189k–$278k",level:"Senior",lane:"Infrastructure security",fit:"",signals:["Kubernetes","Security","Cloud"],posted:"11d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-ec552cbf"},
  {company:"Salesforce",title:"FDE — Public Sector, Nonprofit & Education",region:"US",location:"Remote · United States",salary:"$89k–$288k",level:"Mid–Senior",lane:"Public sector",fit:"",signals:["Salesforce","AI","Architecture"],posted:"12d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-fde-public-sector-nonprofit-education-e12904c9"},
  {company:"AHEAD",title:"Forward Deployed Engineer — AI SOC",region:"US",location:"Remote · United States",salary:"$160k–$200k",level:"Senior",lane:"Security AI",fit:"",signals:["SIEM","Python","Cloud"],posted:"14d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-ai-soc-5cf505ba"},
  {company:"Hims & Hers",title:"Staff Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$195k–$240k",level:"Staff",lane:"Healthtech",fit:"",signals:["AI","Healthcare","Full-stack"],posted:"13d",url:"https://www.fwddeploy.com/jobs/staff-forward-deployed-engineer-5273eb20"},
  {company:"Harness",title:"Customer Architect — Forward Deployed Engineer",region:"Global",location:"Remote",salary:"$160k–$180k",level:"Senior",lane:"DevOps",fit:"",signals:["CI/CD","Cloud","Architecture"],posted:"13d",url:"https://www.fwddeploy.com/jobs/customer-architect-forward-deployed-engineer-0eab969f"},
  {company:"SentinelOne",title:"Senior Staff Forward Deployed Engineer, AI",region:"US",location:"Remote · United States",level:"Senior Staff",lane:"Security AI",fit:"",signals:["AI","Security","Cloud"],posted:"12d",url:"https://www.fwddeploy.com/jobs/senior-staff-forward-deployed-engineer-ai-d8022583"},
  {company:"Parloa",title:"Senior Forward Deployed Engineer",region:"Europe",location:"Remote · Spain",level:"Senior",lane:"Conversational AI",fit:"",signals:["Voice AI","Integrations","Cloud"],posted:"17d",url:"https://www.fwddeploy.com/jobs/senior-forward-deployed-engineer-spain-f0248a28"},
  {company:"talentpluto",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$160k–$200k",level:"Mid–Senior",lane:"Applied AI",fit:"",signals:["AI","Full-stack","Delivery"],posted:"13d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-941fa703"},
  {company:"SentinelOne",title:"Staff Forward Deployed Engineer, AI",region:"US",location:"Remote · United States",level:"Staff",lane:"Security AI",fit:"",signals:["AI","Security","Customer delivery"],posted:"12d",url:"https://www.fwddeploy.com/jobs/staff-forward-deployed-engineer-ai-62869fb7"},
  {company:"Demodesk",title:"Forward Deployed Engineer",region:"Europe",location:"Remote · DACH",level:"Mid–Senior",lane:"Revenue AI",fit:"",signals:["Python","TypeScript","CRM"],posted:"12d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-763bf945"},
  {company:"Alkira",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$150k–$200k",level:"Senior",lane:"Cloud networking",fit:"",signals:["Networking","Cloud","Security"],posted:"15d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-c00123e6"},
  {company:"k-ID",title:"Forward Deployed Engineer, Japan",region:"Global",location:"Remote · Japan / Singapore",level:"Senior",lane:"Identity infrastructure",fit:"",signals:["APIs","Next.js","Security"],posted:"15d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-japan-098f75f3"},
  {company:"Tiger Analytics",title:"Forward Deployed Engineer — Generative AI",region:"US",location:"Remote · United States",level:"Mid–Senior",lane:"Generative AI",fit:"",signals:["GenAI","Python","Data"],posted:"14d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-generative-ai-eafa75bc"},
  {company:"Cohesity",title:"Forward Deployed Engineering Leader",region:"Global",location:"Remote · UK / US",salary:"$229.6k–$287k",level:"Leader",lane:"Data security",fit:"",signals:["Security","Data","Leadership"],posted:"14d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineering-leader-bfac0b54"},
  {company:"RunSybil",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$215k–$245k",level:"Senior",lane:"Applied AI",fit:"",signals:["AI","Full-stack","Product"],posted:"14d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-4b07117b"},
  {company:"OneStream",title:"AI Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$120k–$149k",level:"Mid–Senior",lane:"Finance AI",fit:"",signals:["AI","Finance","Enterprise"],posted:"14d",url:"https://www.fwddeploy.com/jobs/ai-forward-deployed-engineer-4495e728"},
  {company:"Atlassian",title:"Principal Forward Deployed Architect",region:"US",location:"Remote · United States",salary:"$171.8k–$224.3k",level:"Principal",lane:"Enterprise software",fit:"",signals:["Architecture","Platform","AI"],posted:"2mo",url:"https://www.fwddeploy.com/jobs/principal-forward-deployed-architect-a594c3d7"},
  {company:"Outmarket",title:"Forward Deployed AI Engineer",region:"India",location:"Remote · US or India",level:"Mid–Senior",lane:"Insurance AI",fit:"",signals:["Python","LLM","Insurance"],posted:"Live",url:"https://outmarket.ai/careers/forward-deployed-ai-engineer",featured:true},
  {company:"Deployment.io",title:"Forward Deployed Engineer",region:"India",location:"Remote · US or India",level:"2–5 years",lane:"Cloud delivery",fit:"",signals:["AI agents","Docker","Cloud"],posted:"Evergreen",url:"https://deployment.io/careers/",featured:true},
  {company:"PwC",title:"Forward Deployed Data Engineering — Experienced Associate",region:"US",location:"New York City · United States",salary:"$63k–$153k",level:"Mid",lane:"Data engineering",fit:"",signals:["Python","Scala","CI/CD"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"PwC",title:"Forward Deployed Data Engineering — Senior Associate",region:"US",location:"New York City · United States",salary:"$77k–$214k",level:"Senior",lane:"Data engineering",fit:"",signals:["Python","Scala","Data"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"PwC",title:"Forward Deployed Data Engineering — Senior Manager",region:"US",location:"New York City · United States",salary:"$124k–$335k",level:"Senior Manager",lane:"Data engineering",fit:"",signals:["Data","Scala","REST"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"PwC",title:"Forward Deployed Software Engineering — Senior Manager",region:"US",location:"New York City · United States",salary:"$124k–$335k",level:"Senior Manager",lane:"Software delivery",fit:"",signals:["Python","Java","CI/CD"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"PwC",title:"Forward Deployed Software Engineering — Manager",region:"US",location:"New York City · United States",salary:"$99k–$266k",level:"Manager",lane:"Software delivery",fit:"",signals:["Microservices","JavaScript","Data"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"PwC",title:"Forward Deployed Software Engineering — Senior Associate",region:"US",location:"New York City · United States",salary:"$77k–$214k",level:"Senior",lane:"Software delivery",fit:"",signals:["Python","JavaScript","CI/CD"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"PwC",title:"Forward Deployed Software Engineering — Experienced Associate",region:"US",location:"New York City · United States",salary:"$63k–$153k",level:"Mid",lane:"Software delivery",fit:"",signals:["Java","Python","Data"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"Oracle",title:"Lead Principal Application Software Engineer — FDE",region:"US",location:"Pleasanton, CA · United States",salary:"$104.6k–$264.1k",level:"Principal",lane:"Enterprise cloud",fit:"",signals:["Java","Python","Azure"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"JLL",title:"Forward Deployed Engineer",region:"US",location:"San Francisco, CA · United States",salary:"$280k–$300k",level:"Senior",lane:"Proptech AI",fit:"",signals:["Kubernetes","AWS","GCP"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"Insight Enterprises",title:"Forward Deployed Engineer",region:"Global",location:"Canada · Remote eligible",level:"Entry",lane:"Enterprise delivery",fit:"",signals:["Cloud","Integrations","Customer delivery"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"Accenture",title:"Forward Deployed Engineer Manager",region:"Europe",location:"Rome · Italy",salary:"€50k–€86.7k",level:"Manager",lane:"Enterprise AI",fit:"",signals:["Agentic AI","Claude","Microservices"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"Deloitte",title:"Palantir Associate Forward Deployed Engineer — GPS",region:"US",location:"United States · Multiple cities",salary:"$91.1k–$175.1k",level:"Mid",lane:"Public sector data",fit:"",signals:["Palantir","Azure","AWS"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"BNY",title:"SVP, Forward Deployed Engineer",region:"US",location:"Pittsburgh, PA · United States",salary:"$104k–$210k",level:"Senior",lane:"Financial services",fit:"",signals:["Python","TypeScript","Agentic AI"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"UKG",title:"Forward Deployed Engineer III",region:"US",location:"Remote · Seattle / United States",salary:"$102.3k–$169k",level:"Senior",lane:"Workforce tech",fit:"",signals:["Integrations","Cloud","Enterprise"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"Red Cell Partners",title:"Forward Deployed Engineer — Federal / National Security",region:"US",location:"Remote · United States",salary:"$180k–$240k",level:"Senior",lane:"National security",fit:"",signals:["Kubernetes","Python","Security"],posted:"Today",url:"https://deployaijobs.com/jobs"},
  {company:"Dropzone AI",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Senior",lane:"Security AI",fit:"",signals:["SOC","AI agents","Workflows"],posted:"6d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-c50584dc"},
  {company:"GenLogs",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Mid–Senior",lane:"Freight intelligence",fit:"",signals:["Python","TypeScript","SQL"],posted:"23d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-ec62aa13"},
  {company:"Zendesk",title:"Forward Deployed Engineer — AI & Solutions",region:"US",location:"Remote eligible · United States",salary:"$200k–$300k OTE",level:"Senior",lane:"Customer operations",fit:"",signals:["LLM","Data pipelines","AI agents"],posted:"25d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-ad388423",featured:true},
  {company:"OpenHands",title:"Forward Deployed Engineer — Post Sales",region:"Global",location:"Remote · ET / UTC overlap",salary:"$175k–$240k",level:"Senior",lane:"AI coding agents",fit:"",signals:["Python","Rust","MCP"],posted:"15d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-8bf26185",featured:true},
  {company:"Cyclotron",title:"Forward Deployed Engineer — AI",region:"US",location:"Remote · US or Canada",salary:"$165k–$225k",level:"Senior",lane:"Enterprise agents",fit:"",signals:["Azure OpenAI","Copilot","Python"],posted:"Current",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-ai-2ffc1698"},
  {company:"Ravenna",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$130k–$180k",level:"Mid–Senior",lane:"Operations software",fit:"",signals:["Integrations","Product","Customer delivery"],posted:"14d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-2c4e7208"},
  {company:"Duvo",title:"Forward Deployed Engineer",region:"US",location:"Remote-first · United States",level:"Mid–Senior",lane:"AI operations",fit:"",signals:["AI agents","Scripting","Integrations"],posted:"29d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-us-based-633e4e84"},
  {company:"Endava",title:"Senior Forward Deployed Engineer — Palantir",region:"US",location:"Remote · United States",level:"Senior",lane:"Healthcare data",fit:"",signals:["Palantir Foundry","Data","Healthcare"],posted:"2d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-57079ade"},
  {company:"Catena",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Senior",lane:"Agent governance",fit:"",signals:["AI agents","Fintech","Full-stack"],posted:"10d",url:"https://www.fwddeploy.com/jobs/forward-deployed-engineer-f9bb3189"},
  {company:"Nebius",title:"Forward Deployed Engineer — Physical AI",region:"US",location:"Remote · United States",salary:"$169.9k–$254.9k",level:"Senior",lane:"Physical AI",fit:"",signals:["AI infrastructure","Kubernetes","Robotics"],posted:"3w",url:"https://deployaijobs.com/jobs/forward-deployed-engineer-physical-ai-nebius-united-states-remote-21987/"},
  {company:"Vista Equity Partners",title:"Senior Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$200k–$315k",level:"Senior",lane:"Portfolio technology",fit:"",signals:["Python","TypeScript","Cloud"],posted:"1mo",url:"https://deployaijobs.com/jobs/21423-senior-forward-deployed-engineer-vista-equity-partners-united-states-remote/"},
  {company:"Databricks",title:"Senior Forward Deployed Engineer — Retail",region:"US",location:"Remote · United States",salary:"$182k–$250.2k",level:"Senior",lane:"Retail data + AI",fit:"",signals:["Databricks","Python","Spark"],posted:"Today",url:"https://deployaijobs.com/"},
  {company:"Databricks",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$152.9k–$210.2k",level:"Mid–Senior",lane:"Data + AI platform",fit:"",signals:["Databricks","Cloud","Data"],posted:"Today",url:"https://deployaijobs.com/"},
  {company:"Blue Orange Digital",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$150k–$185k",level:"Mid–Senior",lane:"Applied data + AI",fit:"",signals:["Python","SQL","Azure"],posted:"Today",url:"https://deployaijobs.com/"},
  {company:"OpenAI",title:"Technical Deployment Lead — Forward Deployed Engineering",region:"Europe",location:"Remote eligible · London",level:"Lead",lane:"Frontier AI",fit:"",signals:["LLM","Enterprise","Deployment"],posted:"1d",url:"https://deployaijobs.com/jobs?location=United+Kingdom",featured:true},
  {company:"OpenAI",title:"Forward Deployed Engineer",region:"Europe",location:"London · United Kingdom",level:"Senior",lane:"Frontier AI",fit:"",signals:["Python","LLM","Enterprise"],posted:"1w",url:"https://deployaijobs.com/jobs?location=United+Kingdom",featured:true},
  {company:"Typeform",title:"Senior Forward Deployed Engineer",region:"Europe",location:"Remote · United Kingdom",level:"Senior",lane:"Customer experience AI",fit:"",signals:["LLM","Cloud","Integrations"],posted:"4d",url:"https://deployaijobs.com/jobs?location=United+Kingdom"},
  {company:"Legora",title:"Forward Deployed Engineer — SE",region:"Europe",location:"Sweden / UK · Europe",level:"Mid–Senior",lane:"Legal AI",fit:"",signals:["Rust","Data pipelines","SAML"],posted:"1d",url:"https://deployaijobs.com/jobs?location=United+Kingdom"},
  {company:"Barclays",title:"Senior Forward Deployed AI Engineer",region:"Europe",location:"United Kingdom",level:"Senior",lane:"Banking AI",fit:"",signals:["AWS","Python","Rust"],posted:"1d",url:"https://deployaijobs.com/jobs?location=United+Kingdom"},
  {company:"C3 AI",title:"Forward Deployed Engineer",region:"Europe",location:"London · United Kingdom",level:"Senior",lane:"Enterprise AI",fit:"",signals:["Python","React","AI"],posted:"2d",url:"https://deployaijobs.com/jobs?location=United+Kingdom"},
  {company:"Scale AI",title:"Sr Staff ML Forward Deployed Engineer — Enterprise GenAI",region:"Europe",location:"London · United Kingdom",level:"Senior Staff",lane:"Enterprise GenAI",fit:"",signals:["ML","Kubernetes","Python"],posted:"3d",url:"https://deployaijobs.com/jobs?location=United+Kingdom"},
  {company:"Just Eat Takeaway.com",title:"Senior Forward Deployed Engineer",region:"Europe",location:"London · United Kingdom",level:"Senior",lane:"Marketplace systems",fit:"",signals:["Rust","AI","APIs"],posted:"3d",url:"https://deployaijobs.com/jobs?location=United+Kingdom"},
  {company:"Meticulous",title:"Forward Deployed Engineer",region:"Europe",location:"London · United Kingdom",salary:"£150k–£300k",level:"Senior / Staff",lane:"Developer tools",fit:"",signals:["AI agents","OpenAI","Product"],posted:"5d",url:"https://deployaijobs.com/jobs?location=United+Kingdom"},
  {company:"Antithesis",title:"Forward Deployed Engineer",region:"Europe",location:"London · United Kingdom",salary:"£65k–£85k",level:"Mid–Senior",lane:"Reliability testing",fit:"",signals:["Distributed systems","Rust","Customer delivery"],posted:"6d",url:"https://deployaijobs.com/jobs?location=United+Kingdom"},
  {company:"IFS",title:"Forward Deployed AI Engineer — IFS Loops",region:"Europe",location:"London · United Kingdom",salary:"$150k–$170k",level:"Mid–Senior",lane:"Enterprise agents",fit:"",signals:["Python","LLM","Oracle"],posted:"1w",url:"https://deployaijobs.com/jobs?location=United+Kingdom"},
  {company:"LiveKit",title:"Forward Deployed Engineer",region:"Europe",location:"Remote · United Kingdom",salary:"£126k–£185k",level:"Senior",lane:"Real-time AI",fit:"",signals:["Python","Rust","Voice AI"],posted:"1w",url:"https://deployaijobs.com/jobs?location=United+Kingdom"},
  {company:"Ophelos",title:"Forward Deployed Engineer",region:"Europe",location:"Remote · United Kingdom",level:"Mid–Senior",lane:"Fintech operations",fit:"",signals:["Python","TypeScript","Kubernetes"],posted:"1w",url:"https://deployaijobs.com/jobs?location=United+Kingdom"},
  {company:"Salesforce",title:"Forward Deployed Engineer",region:"Europe",location:"London · United Kingdom",level:"Mid–Senior",lane:"Enterprise AI",fit:"",signals:["Python","Java","Salesforce"],posted:"1w",url:"https://deployaijobs.com/jobs?location=United+Kingdom"},
  {company:"CoLab Software",title:"Forward Deployed Engineer",region:"Global",location:"Remote · US or Canada",level:"Mid–Senior",lane:"Engineering collaboration",fit:"",signals:["APIs","Customer success","AI"],posted:"1d",url:"https://deployaijobs.com/api-jobs/"},
  {company:"Irth Solutions",title:"Forward Deployed Engineer — Implementation",region:"Global",location:"Remote · Canada",level:"Mid–Senior",lane:"Infrastructure operations",fit:"",signals:["Azure","Python","SQL"],posted:"3d",url:"https://deployaijobs.com/api-jobs/"},
  {company:"Monte Carlo",title:"Junior Applied Forward Deployed Engineer",region:"US",location:"Remote · United States / New York",salary:"$140k–$180k",level:"Junior",lane:"Data observability",fit:"",signals:["Python","SQL","APIs"],posted:"1w",url:"https://deployaijobs.com/api-jobs/"},
  {company:"Juniper Square",title:"Senior Forward Deployed Engineer — AI",region:"US",location:"Remote · United States",salary:"$170k–$220k",level:"Senior",lane:"Private markets AI",fit:"",signals:["AI","APIs","Fintech"],posted:"1w",url:"https://deployaijobs.com/api-jobs/"},
  {company:"ONE",title:"Forward Deployed Engineer — AI & Automation",region:"US",location:"Remote · United States",salary:"$170k–$210k",level:"Senior",lane:"Fintech automation",fit:"",signals:["AWS","Kubernetes","Automation"],posted:"1w",url:"https://deployaijobs.com/api-jobs/"},
  {company:"StackAI",title:"Forward Deployed Engineer — Spanish Speaking",region:"US",location:"Remote · United States",salary:"$120k–$200k",level:"Mid–Senior",lane:"Enterprise agents",fit:"",signals:["Python","TypeScript","LLM"],posted:"1w",url:"https://deployaijobs.com/api-jobs/"},
  {company:"Red Hat",title:"Forward Deployed Engineer — AI Inference",region:"US",location:"Remote · United States",salary:"$184.9k–$342.5k",level:"Senior",lane:"AI infrastructure",fit:"",signals:["vLLM","Kubernetes","Python"],posted:"1w",url:"https://deployaijobs.com/api-jobs/"},
  {company:"Relyance AI",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$220k–$250k",level:"Senior",lane:"Data governance",fit:"",signals:["Cloud","SQL","APIs"],posted:"1w",url:"https://deployaijobs.com/api-jobs/"},
  {company:"Picarro",title:"Forward Deployed Engineer — Oil, Gas & Chemicals",region:"US",location:"Remote · United States",salary:"$100k–$150k",level:"Mid–Senior",lane:"Climate intelligence",fit:"",signals:["React","APIs","Industrial data"],posted:"1w",url:"https://deployaijobs.com/api-jobs/"},
  {company:"Kong",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$133.1k–$190.1k",level:"Senior",lane:"API infrastructure",fit:"",signals:["Kubernetes","Java","Cloud"],posted:"1w",url:"https://deployaijobs.com/api-jobs/"},
  {company:"Maybern",title:"Senior Forward Deployed Engineer",region:"US",location:"Remote · United States",salary:"$145k–$185k",level:"Senior",lane:"Private markets",fit:"",signals:["Python","SQL","Rails"],posted:"1w",url:"https://deployaijobs.com/api-jobs/"},
  {company:"GitLab",title:"Forward Deployed Engineer",region:"Europe",location:"Remote · United Kingdom",level:"Senior",lane:"DevSecOps",fit:"",signals:["Ruby on Rails","APIs","GitLab"],posted:"1w",url:"https://deployaijobs.com/api-jobs/"},
  {company:"GitLab",title:"Field Strategist — Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Senior",lane:"DevSecOps",fit:"",signals:["Rails","APIs","Enterprise"],posted:"1w",url:"https://deployaijobs.com/api-jobs/"},
  {company:"Resilinc",title:"Forward Deployed Engineer — Enterprise AI Solutions",region:"India",location:"Remote · India",level:"Mid–Senior",lane:"Supply-chain AI",fit:"",signals:["Python","LLM","APIs"],posted:"1w",url:"https://deployaijobs.com/api-jobs/",featured:true},
  {company:"OpenRouter",title:"Forward Deployed Engineer",region:"US",location:"Remote · United States",level:"Senior",lane:"LLM infrastructure",fit:"",signals:["Python","TypeScript","LLM"],posted:"1w",url:"https://deployaijobs.com/api-jobs/",featured:true},
];

const regions = ["All", "US", "Europe", "India", "Global"] as const;

export default function Home() {
  const [region, setRegion] = useState<(typeof regions)[number]>("All");
  const [query, setQuery] = useState("");
  const [onlySalary, setOnlySalary] = useState(false);
  const visible = useMemo(() => jobs.filter((job) => {
    const regionMatch = region === "All" || job.region === region;
    const haystack = `${job.company} ${job.title} ${job.lane} ${job.signals.join(" ")}`.toLowerCase();
    return regionMatch && (!onlySalary || Boolean(job.salary)) && haystack.includes(query.toLowerCase());
  }), [region, query, onlySalary]);

  return <main>
    <div className="wrap">
      <header className="hero">
        <a className="eyebrow bootcamp-link" href="https://maven.com/boring-bot/ai-system-design" target="_blank" rel="noreferrer">GUIDED ASSET FOR THE AI SYSTEM DESIGN BOOTCAMP ↗</a>
        <h1>Forward Deployed<br/><span>Engineer Jobs.</span></h1>
        <p className="dek">Remote and remote-eligible roles across the US, Europe, and India.</p>
        <div className="hero-meta"><span>{jobs.length} current roles</span><span>US · Europe · India</span><span>Checked 28 Jul 2026</span></div>
        <div className="rule" />
      </header>

      <section id="roles">
        <span className="kicker">OPEN ROLES</span><h2>Find your next FDE role.</h2>
        <p className="sub">Filter by hiring region, skills, company, or published compensation.</p>
        <div className="toolbar">
          <div className="tabs" role="group" aria-label="Filter by region">{regions.map(r => <button key={r} className={region === r ? "active" : ""} onClick={() => setRegion(r)}>{r}</button>)}</div>
          <label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search skill, company, lane…" aria-label="Search roles"/></label>
          <label className="check"><input type="checkbox" checked={onlySalary} onChange={e=>setOnlySalary(e.target.checked)}/><span/> Pay shown</label>
        </div>
        <div className="count">SHOWING {visible.length} OF {jobs.length} ROLES</div>
        <div className="jobs">{visible.map(job => <article className={`job ${job.featured ? "featured" : ""}`} key={`${job.company}-${job.title}-${job.location}`}>
          <div className="job-top"><div className="logo">{job.company.slice(0,2).toUpperCase()}</div><div className="job-title"><div className="company">{job.company}{job.featured && <span className="pick">EDITOR’S PICK</span>}</div><h3>{job.title}</h3></div><a className="apply" href={job.url} target="_blank" rel="noreferrer" aria-label={`View ${job.title} at ${job.company}`}>View role ↗</a></div>
          <div className="facts"><span>◎ {job.location}</span><span>◈ {job.level}</span>{job.salary && <span className="salary">{job.salary}</span>}<span className="posted">{job.posted}</span></div>
          <div className="tags"><span className="lane">{job.lane}</span>{job.signals.map(s=><span key={s}>{s}</span>)}</div>
        </article>)}</div>
        {visible.length === 0 && <div className="empty">No roles match this lens. Try a broader region or search.</div>}
      </section>
      <footer><div><b>FDE JOB BOARD</b><a href="https://maven.com/boring-bot/ai-system-design" target="_blank" rel="noreferrer">A guided asset for the AI System Design bootcamp ↗</a></div><p>Checked 28 Jul 2026 using employer pages, FWDDeploy and DeployAI Jobs. Confirm eligibility before applying.</p></footer>
    </div>
  </main>;
}
